### label and ordinal encoding  -->

In [76]:
import numpy as np
import pandas as pd

In [77]:
df = pd.read_csv('customer.csv')
df.head(3)

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No

In [78]:
df = df.iloc[:,2:]
df.head(3)

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No

In [79]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop('purchased',axis=1),
                                                 df['purchased'],
                                                 train_size=.7,
                                                 random_state=42 
                                                 )
x_train.shape, x_test.shape

((35, 2), (15, 2))

In [80]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
x_train=oe.fit_transform(x_train)
x_test = oe.transform(x_test)

In [81]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [82]:
y_train=le.fit_transform(y_train)
y_test = le.transform(y_test)

In [83]:
y_train

array([0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])